appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
bot:
  automerge: true
provider:
  win: azure
travis:
  secure:
    BINSTAR_TOKEN: XXAq7cUfVM3nKpz+/zNWeEfm9T39Yb7UP5ZGJp6yYKuRnbZH5W00zOBYs5EBZQdmJO24q4O7jkSUPyQBsHgn/GhYLAYOIbTC6GcoMtxsOCTtBEHn3g5+LH4O5KiCuHZyKTUgt6ASQnYOVjHr5BkzNJHlMlXQHAC8hKMnehmJzozR1liCq7r3UqnMc3ej71jJdAN/TAcHPmM8u+uAkXal00OliS1IbpNX5aUpecjq9eQTAdo/aYzz4o4wriQ0Sj0IhCxTGECinAh0A26lKa9d5yOYgxvKWNzclPO3iG8XyEDPqxhZYkpVl48JlC5L2Dts0pAv8zMcfc29F1bRXUKkNeTTcR9C5XRy+N2P2e0AAF7jmNwJMxO7aJt77phkhqr4Xx9cxzsinDAf00TBsziCj+1vtcJCpLcBGM/3Yvy6DHojBFAL5pdU/+FaY1iGwHYTXtdN2KNPUPJIAX+Ch5VoXjcn5WPdxpXStL35en0dZXTB/pN6u1jasT6tuiuPKcC6n5Nn+2Wr26sWYDPy+HQzCy7OX91tL0JYMfFr50mOL4e+CgACt1EU/cSYYsRt+MfSVRwD5TYBDERF1QLqteoClrKc1A7Cg7JjlJA5ImzIfCCCrZTMEn8CtsefAEdVRWhc29ZgH9fotqb47jwdfrG8FCLEF0+GLQYdZhsURGAPKO4=
conda_forge_output_validation: true
